### PR TITLE
Use Oauth2 login with spotify

### LINKED ISSUE #726: Incorrect login credentials
**Describe the bug**
I cant authenticate to my Spotify account using the Spot client, no matter the account or how many times i reset the password, i get the "Incorrect login credentials". Same credentials work on other devices/clients.

**To Reproduce**
1. Install Spot (Flatpak)
2. Type credentials
3. Click "Log in"

**Expected behavior**
Sign into my account

**Screenshots**
image

**General information:**
 - Distribution: Arch Linux
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.4.1
 - Device used [e. g. desktop, phone...]: desktop

**Additional context**
I found another guy on the Gnome Software review section saying he had the same problem, I installed Spot on this same machine back in June and used it normally, after reinstalling the system, i get this error.

### LINKED ISSUE #728: Cannot Log Back In
**Describe the bug**
I opened Spot today. Playback didn't work. Reopened it, and it logged me out. I can't log back in. I can only reproduce what happens when I open it now (since it logged me out).

**To Reproduce**
1. Open Spot
2. Enter email (or username) and password
3. See error

**Expected behavior**
I am logged in.

**Screenshots**
image

**General information:**
 - Distribution: Fedora Linux 40 (Workstation Edition)
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.4.1
 - Device used [e. g. desktop, phone...]: Desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
```

**Additional context**
Add any other context about the problem here._

### LINKED ISSUE #729: Any chances of a dependency bump?
This is just an issue to raise awareness:
Quote from @aleksrutins:
"It seems like librespot has fixed this issue upstream - any chance of a dependency bump?"
Thank you.
https://github.com/xou816/spot/issues/728#issuecomment-2351729051

### PR DESCRIPTION
**Pull request by stevenleadbeater**
fixes #729, fixes #728 and fixes #726

works for me locally, I preserved the original login method, added a new one for login with spotify and fixed an issue that stopped tracks playing. I'm not massively familiar with this code (I pulled it yesterday because I wanted it to work on my pinephone) I'm happy to do a bit more to get this mergeable if needed but please bear in mind I may need a bit of guidance on what files to look at to solve issues

### CODE REVIEW

**Comment by stevenleadbeater** [comment]
That flatpak builder failure looks like clippy complaining about pre-existing code. Is this a new thing?

**Comment by stevenleadbeater** [comment]
tested it on my pinephone too and I have tunes :)

**Review by davidosdr — APPROVED** [review]
It seems ok for me, I got it working on my laptop with this

**Review by NatryN — APPROVED** [review]

**Review by schooldanlp6 — APPROVED** [review]
but it should work with librespot 0.6.0 too which is also what I run on my OS currently

but thanks for the fix it works now :))))

**Review by schooldanlp6 — APPROVED** [review]

**Review by skoruppa — APPROVED** [review]

**Comment by stevenleadbeater** [comment]
> but it should work with librespot 0.6.0 too which is also what I run on my OS currently
> 
> but thanks for the fix it works now :))))

You must have commented 0.6.0 within days of it's release :') I'll give it a go and see how it works. I was actually looking at the login5 stuff on librespot too as it may fix the other authentication issue....

**Comment by alumni** [comment]
I also tested it locally and it seems it's working quite well. I would remove the old login button.

@xou816 Could you review?

**Comment by xou816** [comment]
<usual busy excuse here>
Looks like a lot of great work, I'll try to review that tomorrow, thanks!

File: src/player/player.rs [hunk 1]
```diff
@@ -278,7 +311,8 @@ impl SpotifyPlayer {
     }
 }
 
-const CLIENT_ID: &str = "782ae96ea60f4cdf986a766049607005";
+const REDIRECT_URI: &str = "http://127.0.0.1:8898/login";
+const SPOTIFY_CLIENT_ID: &str = "65b708073fc0480ea92a077233ca87bd";
```
Comment (xou816) [inline src/player/player.rs]: does the client id need to change? i guess we should eventually make this configurable

**Comment by xou816** [comment]
Looks good overall! I would have a few things to nitpick but nothing major/no reason to delay this. Just hesitant about the client id change, is it needed?

File: src/app/components/login/login.blp [hunk 2]
```diff
@@ -94,6 +94,13 @@ template $LoginWindow : Adw.Window {
             halign: center;
             styles ["pill", "suggested-action"]
           }
+
+          Button login_with_spotify_button {
+            /* Translators: Log in button label */
+            label: _("Log in with Spotify");
```
Comment (xou816) [inline src/app/components/login/login.blp]: the wording could probably be improved to make it clear its an external login, but I dont have any great suggestion just yet; probably need to review the whole ui of this dialog!

File: src/api/oauth2.rs [hunk 3]
```diff
@@ -0,0 +1,293 @@
...
+        .map(|s| Scope::new(s.into()))
+        .collect();
+    let (auth_url, _) = client
+        .authorize_url(CsrfToken::new_random)
+        .add_scopes(request_scopes)
+        .set_pkce_challenge(pkce_challenge)
+        .url();
+
+    println!("Browse to: {}", auth_url);
+    if let Err(err) = open::that(auth_url.to_string()) {
```
Comment (xou816) [inline src/api/oauth2.rs:248]: I'm not super clear on the benefits, but I'd be interested in doing that with portals/ASPHD at some later time!

File: src/api/oauth2.rs [hunk 4]
```diff
@@ -0,0 +1,293 @@
...
+        eprintln!("An error occurred when opening '{}': {}", auth_url, err)
+    }
+
+    let code = match get_socket_address(redirect_uri) {
+        Some(addr) => get_authcode_listener(addr),
+        _ => get_authcode_stdin(),
+    }?;
+    trace!("Exchange {code:?} for access token");
+
+    // Do this sync in another thread because I am too stupid to make the async version work.
```
Comment (xou816) [inline src/api/oauth2.rs:258]: that's absolutely fine that can be adressed later :smile:

File: src/api/oauth2.rs [hunk 5]
```diff
@@ -0,0 +1,293 @@
...
+    let token = token_response.map_err(|e| OAuthError::ExchangeCode { e: e.to_string() })?;
+    trace!("Obtained new access token: {token:?}");
+
+    let token_scopes: Vec<String> = match token.scopes() {
+        Some(s) => s.iter().map(|s| s.to_string()).collect(),
+        _ => scopes.into_iter().map(|s| s.to_string()).collect(),
+    };
+    let refresh_token = match token.refresh_token() {
+        Some(t) => t.secret().to_string(),
+        _ => "".to_string(), // Spotify always provides a refresh token.
```
Comment (xou816) [inline src/api/oauth2.rs]: should this trigger an error then?

File: src/api/oauth2.rs [hunk 6]
```diff
@@ -0,0 +1,293 @@
...
+            error!("OAuth channel send error: {e}");
+        }
+    });
+    let token_response = rx.recv().map_err(|_| OAuthError::Recv)?;
+    let token = token_response.map_err(|e| OAuthError::ExchangeCode { e: e.to_string() })?;
+    trace!("Obtained new access token: {token:?}");
+
+    let token_scopes: Vec<String> = match token.scopes() {
+        Some(s) => s.iter().map(|s| s.to_string()).collect(),
+        _ => scopes.into_iter().map(|s| s.to_string()).collect(),
```
Comment (xou816) [inline src/api/oauth2.rs]: i guess its technically nullable but not really in practice, maybe it should be an error as well?

File: src/api/oauth2.rs [hunk 7]
```diff
@@ -0,0 +1,293 @@
...
+
+    // Generate the full authorization URL.
+    // Some of these scopes are unavailable for custom client IDs. Which?
+    let request_scopes: Vec<oauth2::Scope> = scopes
+        .clone()
+        .into_iter()
+        .map(|s| Scope::new(s.into()))
+        .collect();
+    let (auth_url, _) = client
+        .authorize_url(CsrfToken::new_random)
```
Comment (xou816) [inline src/api/oauth2.rs:242]: should this token be validated somewhere down the line?

File: src/app/components/details/release_details.rs [hunk 8]
```diff
@@ -57,6 +57,12 @@ glib::wrapper! {
     pub struct ReleaseDetailsWindow(ObjectSubclass<imp::ReleaseDetailsWindow>) @extends gtk::Widget, libadwaita::Window, libadwaita::PreferencesWindow;
 }
 
+impl Default for ReleaseDetailsWindow {
```
Comment (xou816) [inline src/app/components/details/release_details.rs:60]: thanks for taking care of clippy :sweat_smile:

**Review by xou816 — COMMENTED** [review]
(nothing blocking, just want to discuss the client id real quick)

**Review by AlexsandroBezerra — APPROVED** [review]

File: src/player/player.rs (hunk 1 above)
Comment (xou816) [reply src/player/player.rs]: updated my client to allow the expected redirect uris, if you want to revert that!

**Review by nklsfrt — APPROVED** [review]

**Comment by stevenleadbeater** [comment]
Hi @xou816 :wave:  nice to meet you. I'll have a look through your comments, I did kind of just lift and shift the oauth2 code out of librespot as it was `println`ing the auth URI but I'm still happy to fix it up :heart: specifically the client ID, first shot with the existing didn't work for me as the return URI is a 127.0.0.1 address and I don't know how your return URI was configured so I took a pivot and used the client ID that librespot used :see_no_evil: if yours works I'm happy to do the reversion :angel:

**Comment by xou816** [comment]
hi! :) no yeah you're right I had not thought of this initally, you had no choice in order to test! but yeah it can be reverted, the client is now configured with the expected redirect uris

as for the rest dont worry about it too much, that can all be adressed later, i dont mind too much, your MR brings a lot of long needed fixes so thats the priority!

**Comment by xou816** [comment]
looks like the refresh token is not being used when re-opening Spot at a later time, I'll look into that

**Comment by xou816** [comment]
I pushed a few modifications hope you don't mind!

**Comment by stevenleadbeater** [comment]
66

> I pushed a few modifications hope you don't mind!

not at all :smile:  I'll fix up the oauth2 stuff this morning and bump librespot to 0.6.0

File: src/api/oauth2.rs (hunk 3 above)
Comment (stevenleadbeater) [reply src/api/oauth2.rs:248]: I don't know what portals?ASPHD is :see_no_evil: is this a browser window you can use in your app? I stuck with opening the default browser because it allowed me to use my password manager on the spotify loging dialog on my postmarketos device :smile:

File: src/api/oauth2.rs (hunk 4 above)
Comment (stevenleadbeater) [reply src/api/oauth2.rs:258]: :laughing: https://github.com/librespot-org/librespot/blob/82076e882f3cdebec863a3c0aa79888ec47b3c76/oauth/src/lib.rs#L212

as much as I'd love to use that file directly, it's just `println`'ing the URL and IDK how to consume that from a library that's writing to the consuming applications std-out

File: src/app/components/login/login.blp (hunk 2 above)
Comment (stevenleadbeater) [reply src/app/components/login/login.blp]: Login with Spotify.com?

File: src/api/oauth2.rs (hunk 4 above)
Comment (stevenleadbeater) [reply src/api/oauth2.rs:258]: I've made some changes in regards to the CSRF token. I will try and get  PR in to librespot for this as it makes more sense to me at least to try and use the default browser...

File: src/api/oauth2.rs (hunk 5 above)
Comment (stevenleadbeater) [reply src/api/oauth2.rs]: fixed

File: src/api/oauth2.rs (hunk 6 above)
Comment (stevenleadbeater) [reply src/api/oauth2.rs]: fixed

File: src/app/components/details/release_details.rs (hunk 8 above)
Comment (stevenleadbeater) [reply src/app/components/details/release_details.rs:60]: :saluting_face:

**Review by schooldanlp6 — APPROVED** [review]
nice that its bumped now to 0.6.0

**Comment by schooldanlp6** [comment]
is the problem with the "you close the app and get logged out" fixed? just curious

**Comment by stevenleadbeater** [comment]
> is the problem with the "you close the app and get logged out" fixed? just curious

I think xou816 fixed that with his push

**Review by xou816 — APPROVED** [review]

File: src/api/oauth2.rs (hunk 3 above)
Comment (xou816) [reply src/api/oauth2.rs:248]: its a terrible (but lovely) name that i always mispell for this lib: https://github.com/bilelmoussaoui/ashpd

**Comment by xou816** [comment]
merged!! thanks for fixing a major issue!

**Comment by xou816** [comment]
i might still need to fix a few things with reopening the app after while -- the token needs to be refreshed

we need to store the refresh token and use that to get a fresh access token after a while

**Comment by stevenleadbeater** [comment]
Thanks @xou816 if you want me to look at anything, feel free to @ me on an issue. I can make some time for spot :heart:
