### PR TITLE
Fix/Improve keyboard navigation for login dialog

### LINKED ISSUE #70: Login doesn't allow user to tab between inputs
**Describe the bug**
Login doesn't allow tabbing between fields

**To Reproduce**
1. Go to login screen
2. Select username
3. Active element doesn't change

**Expected behavior**
Tab switches user selection between username, password and login fields

**General information:**
 - Distribution: Arch
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.1.7

### PR DESCRIPTION
**Pull request by Douile**
This PR fixes tab navigation not working on the login dialog. It also allows the user to submit the login form by pressing return.

Some notes:
- In the key-press handler I added some logic that auto focuses the username or password entry if they are empty. I wasn't sure whether this should go in `LoginModel::login`
  - I also think this should give some user feedback, i.e. logs in but password is empty, then password box is highlighted red and focused. But I don't know how to do this
- The key-press should probably be a method but I wasn't sure where was best to put it.

Fixes #70

### CODE REVIEW

**Comment by xou816** [comment]
(You really should set up rustfmt, it's fast and will save you a lot of trouble :p )

Thank you for the PR! This is a very welcome change!

File: src/app/components/login/login.rs [hunk 1]
```diff
@@ -9,12 +11,37 @@ use crate::app::AppEvent;
 
 use super::LoginModel;
 
+const KEY_RETURN: u32 = 65293;
```
Comment (xou816) [inline src/app/components/login/login.rs:14]: Have you tried using [keyval_from_name](https://gtk-rs.org/docs/gdk/fn.keyval_from_name.html)? Might handle the keycode conversion subtleties for us :)

File: src/app/components/login/login.rs [hunk 2]
```diff
@@ -9,12 +11,37 @@ use crate::app::AppEvent;
...
+    username: gtk::Entry,
+    password: gtk::Entry,
+    model: Rc<LoginModel>,
+    event: &EventKey
+) -> Inhibit {
+    match event.get_keyval().to_glib() {
+        KEY_RETURN => {
+            let username_text = username.get_text().as_str().to_string();
+            let password_text = password.get_text().as_str().to_string();
+            if username_text.len() == 0 {
```
Comment (xou816) [inline src/app/components/login/login.rs:32]: Prefer using [is_empty](https://doc.rust-lang.org/std/string/struct.String.html#method.is_empty) (same below)

File: src/app/components/login/login.rs [hunk 3]
```diff
@@ -32,6 +59,16 @@ impl Login {
                 model.login(username, password);
```
Comment (xou816) [inline src/app/components/login/login.rs:59]: The click handler could use the same handler and logic as below, if we rename it to something like `submit_login_form` or something, idk!

File: src/window.ui [hunk 4]
```diff
@@ -349,7 +349,7 @@
                 <child>
                   <object class="GtkToggleButton" id="shuffle">
                     <property name="visible">True</property>
-                    <property name="can-focus">False</property>
+                    <property name="can-focus">True</property>
```
Comment (xou816) [inline src/window.ui:352]: Is this intentional? Probably since can-focus makes sense here, but I'd rather have this in another PR (there are probably other focus/keyboard navigation issues in the main window too)

Comment (Douile) [reply src/window.ui:352]: It was the only one I noticed in the main window so thought I would throw it in with these. I can remove it if you want though.

File: src/app/components/login/login.rs (hunk 1 above)
Comment (Douile) [reply src/app/components/login/login.rs:14]: I'll look into it

File: src/window.ui (hunk 4 above)
Comment (xou816) [reply src/window.ui:352]: Okay, why not :)

File: src/app/components/login/login.rs (hunk 3 above)
Comment (Douile) [reply src/app/components/login/login.rs]: @xou816 is 06df1a38df18457ab917f0c0182b150db72837f4 what you meant?

**Comment by xou816** [comment]
Oh sorry, I should have answered you earlier about the Model thing: I'm keeping these Model structs mostly to manage interactions with the app state (reading from the state or sending "actions"). I'd actually prefer that submit fn to be on the Login struct :)

**Comment by Douile** [comment]
no problem I will move it

**Comment by xou816** [comment]
LGTM! :) I should make a release tomorrow, I'm glad that this will be part of it!
