### PR TITLE
Provide Application Name to PulseAudio

### LINKED ISSUE #621: Provide a pulseaudio playing stream name
**Describe the bug**
Spot does not provides, or provides an empty name for its playing stream on pulseaudio.

**To Reproduce**
1. Play a song
2. List pulseaudio/pipewire playing stream (with pavucontrol, or wpctl status)
3. The spot stream does not have a name

**Expected behavior**
Provide a meaningful stream name, like "spot".

**General information:**
 - Distribution: archlinux
 - Installation method: AUR
 - Version: 0.4.0

### PR DESCRIPTION
**Pull request by XGZepto**
Fix #621.

image

### CODE REVIEW

File: src/player/player.rs [hunk 1]
```diff
@@ -15,6 +15,7 @@ use librespot::playback::audio_backend;
 use librespot::playback::config::{AudioFormat, Bitrate, PlayerConfig, VolumeCtrl};
 use librespot::playback::player::{Player, PlayerEvent, PlayerEventChannel};
 
+use std::env;
 use std::cell::RefCell;
```
Comment (xou816) [inline src/player/player.rs]:
```suggestion
use std::cell::RefCell;
use std::env;
```

Comment (xou816) [reply src/player/player.rs]: looks like rust fmt isnt happy with the order of the imports

**Review by xou816 — APPROVED** [review]

**Comment by xou816** [comment]
thanks! :)
